import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';

const mcpUrl = process.env.MCP_URL ?? 'http://127.0.0.1:3002/mcp';
const runId = process.env.SMOKE_RUN_ID ?? new Date().toISOString().replace(/[:.]/g, '-');

const requiredTools = [
  'ping',
  'kg_upsert_node',
  'kg_link',
  'kg_recall',
  'kg_ingest_document',
  'kg_get_document_chunks',
  'kg_stats',
];

function payloadOf(result) {
  if (result?.structuredContent) return result.structuredContent;
  const text = result?.content?.find((item) => item.type === 'text')?.text;
  if (!text) return {};
  return JSON.parse(text);
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function main() {
  const client = new Client({ name: 'romanzo-gabriele-neural-smoke', version: '0.1.0' });
  const transport = new StreamableHTTPClientTransport(new URL(mcpUrl));

  await client.connect(transport);

  try {
    const listed = await client.listTools();
    const available = new Set(listed.tools.map((tool) => tool.name));
    for (const tool of requiredTools) assert(available.has(tool), `Missing MCP tool: ${tool}`);

    const call = async (name, args = {}) => {
      const result = await client.callTool({ name, arguments: args });
      const payload = payloadOf(result);
      assert(payload.ok !== false, `${name} failed: ${JSON.stringify(payload.error ?? payload)}`);
      return payload;
    };

    await call('ping');

    const root = await call('kg_upsert_node', {
      type: 'SmokeTest',
      label: `Smoke Root ${runId}`,
      content: `Root node generated by smoke run ${runId}.`,
      metadata: { runId, role: 'root' },
      provenance: { source: 'smoke' },
    });

    const child = await call('kg_upsert_node', {
      type: 'SmokeTest',
      label: `Smoke Child ${runId}`,
      content: `Child node generated by smoke run ${runId}.`,
      metadata: { runId, role: 'child' },
      provenance: { source: 'smoke' },
    });

    assert(root.node?.id, 'kg_upsert_node did not return root node id');
    assert(child.node?.id, 'kg_upsert_node did not return child node id');

    await call('kg_link', {
      fromId: root.node.id,
      toId: child.node.id,
      kind: 'related_to',
      weight: 0.8,
      metadata: { runId },
      provenance: { source: 'smoke' },
    });

    const recall = await call('kg_recall', { query: runId, depth: 1, limit: 5 });
    assert((recall.nodes?.length ?? 0) >= 2, 'kg_recall did not return the smoke graph');

    const sourceId = `smoke-${runId}`;
    const document = await call('kg_ingest_document', {
      sourceId,
      title: `Smoke Document ${runId}`,
      sourceType: 'smoke',
      content: [
        `Smoke document for run ${runId}.`,
        'This content must be persisted through the backend NAS writer.',
        'The MCP service remains the graph writer and document ingestion entrypoint.',
      ].join('\n'),
      chunkSize: 80,
      metadata: { runId },
      provenance: { source: 'smoke' },
    });

    assert(document.document?.id, 'kg_ingest_document did not return a document node');
    assert((document.chunkCount ?? 0) > 0, 'kg_ingest_document did not create chunks');
    assert(document.nas?.saved === true, `kg_ingest_document did not persist source to NAS: ${JSON.stringify(document.nas)}`);

    const chunks = await call('kg_get_document_chunks', { sourceId });
    assert((chunks.chunks?.length ?? 0) === document.chunkCount, 'kg_get_document_chunks returned an unexpected chunk count');

    const stats = await call('kg_stats');
    assert((stats.nodes ?? 0) >= 3, 'kg_stats returned too few nodes after smoke writes');
    assert((stats.edges ?? 0) >= 1, 'kg_stats returned too few edges after smoke writes');

    console.log(JSON.stringify({
      ok: true,
      mcpUrl,
      runId,
      tools: listed.tools.length,
      rootNodeId: root.node.id,
      childNodeId: child.node.id,
      documentNodeId: document.document.id,
      chunkCount: document.chunkCount,
      nasPath: document.nas.path,
      stats: { nodes: stats.nodes, edges: stats.edges },
    }, null, 2));
  } finally {
    await client.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
