export const MCP_TOOL_NAMES = {
  ping: 'ping',
  get_server_status: 'get_server_status',
  list_mcp_capabilities: 'list_mcp_capabilities',
  kg_add_node: 'kg_add_node',
  kg_upsert_node: 'kg_upsert_node',
  kg_upsert_nodes: 'kg_upsert_nodes',
  kg_update_node: 'kg_update_node',
  kg_delete_node: 'kg_delete_node',
  kg_link: 'kg_link',
  kg_link_bulk: 'kg_link_bulk',
  kg_unlink: 'kg_unlink',
  kg_attach_asset: 'kg_attach_asset',
  kg_get_node: 'kg_get_node',
  kg_search: 'kg_search',
  kg_neighbors: 'kg_neighbors',
  kg_recall: 'kg_recall',
  kg_stats: 'kg_stats',
  kg_audit_global: 'kg_audit_global',
  kg_repair: 'kg_repair',
  kg_run_consolidation: 'kg_run_consolidation',
  kg_ingest_document: 'kg_ingest_document',
  kg_get_document_chunks: 'kg_get_document_chunks',
  kg_list_documents: 'kg_list_documents',
  novel_ingest_outline: 'novel_ingest_outline',
  novel_ingest_bible: 'novel_ingest_bible',
  novel_ingest_bible_sections: 'novel_ingest_bible_sections',
  novel_extract_bible_candidates: 'novel_extract_bible_candidates',
  novel_commit_bible_candidates: 'novel_commit_bible_candidates',
  novel_get_bible_ontology: 'novel_get_bible_ontology',
  novel_get_bible_mapping_packet: 'novel_get_bible_mapping_packet',
  novel_bible_coverage_report: 'novel_bible_coverage_report',
  novel_get_chapter_context_packet: 'novel_get_chapter_context_packet',
  novel_ingest_chapter_draft: 'novel_ingest_chapter_draft',
  novel_recall_context: 'novel_recall_context',
  novel_audit_chapter: 'novel_audit_chapter',
  novel_start_editing_session: 'novel_start_editing_session',
  novel_split_chapter_blocks: 'novel_split_chapter_blocks',
  novel_save_editorial_findings: 'novel_save_editorial_findings',
  novel_save_user_decisions: 'novel_save_user_decisions',
  novel_save_rewrite_block: 'novel_save_rewrite_block',
  novel_assemble_chapter_revision: 'novel_assemble_chapter_revision',
  novel_save_seam_review: 'novel_save_seam_review',
  novel_save_final_chapter: 'novel_save_final_chapter',
  novel_create_visual_brief: 'novel_create_visual_brief',
  novel_attach_generated_image: 'novel_attach_generated_image',
} as const;

export type McpToolName = typeof MCP_TOOL_NAMES[keyof typeof MCP_TOOL_NAMES];
export const ALL_MCP_TOOL_NAMES: readonly string[] = Object.values(MCP_TOOL_NAMES);
